config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.urls import re_path
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.http import HttpResponse

from saas_app.views import PricingView


app_name = "saas_app"
urlpatterns = [
    re_path(r"^$", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    re_path(
        r"^health_check/$",
        lambda r: HttpResponse("ok"),
    ),
    re_path(
        r"^terms-and-conditions/$",
        TemplateView.as_view(template_name="pages/terms_and_conditions.html"),
        name="terms_and_conditions",
    ),
    re_path(
        r"^privacy-policy/$",
        TemplateView.as_view(template_name="pages/privacy_policy.html"),
        name="privacy_policy",
    ),
    re_path(r"^pricing/$", PricingView.as_view(), name="pricing"),
    re_path(
        r"^features/$",
        TemplateView.as_view(template_name="pages/features.html"),
        name="features",
    ),
    # Django Admin, use {% url 'admin:index' %}
    re_path(settings.ADMIN_URL, admin.site.urls),
    re_path(r"^api/", include("saas_app.api.urls", namespace="api")),
    re_path(r"^auth/", include("allauth.urls")),
    re_path(
        r"^blog/",
        include("saas_app.blog.urls", namespace="blog"),
    ),
    re_path(r"^tinymce/", include("tinymce.urls")),
    re_path(
        r"^app/",
        include("saas_app.app.urls", namespace="app"),
    ),
    re_path(r"^users/", include("saas_app.users.urls", namespace="users")),
    re_path("", include("saas_app.beta.urls", namespace="beta")),
    # re_path(r"^payments/", include("saas_app.payments.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        re_path(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        re_path(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        re_path(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        re_path(r"^500/$", default_views.server_error),
    ]

saas_app/api/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# from django.conf.urls import include, url
from django.urls import include, re_path

app_name = "api"

urlpatterns = [
    re_path(r"^v1/", include("saas_app.api.v1.urls", namespace="v1")),
]

saas_app/app/urls.py
# -*- coding: utf-8 -*-
# from __future__ import unicode_literals
from django.urls import re_path

from saas_app.app import views

app_name = "app"

urlpatterns = [
    re_path(r"^$", views.DashboardView.as_view(), name="dashboard"),
]

saas_app/beta/urls.py
from django.urls import re_path
from . import views

app_name = "beta"

urlpatterns = [
    re_path(
        r"^request-invite/$",
        views.RequestInviteView.as_view(),
        name="request-invite",
    ),
    re_path(
        r"^request-success/$",
        views.RequestInviteSuccess.as_view(),
        name="request-success",
    ),
]

saas_app/users/urls.py
# -*- coding: utf-8 -*-

from django.urls import re_path, path, include

from . import views

app_name = "users"

urlpatterns = [
    # URL pattern for the UserUpdateView
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    re_path(r"^~update/$", view=views.UserUpdateView.as_view(), name="update"),
]

saas_app/beta/models.py
from model_utils.models import TimeStampedModel

from django.db import models
from django.utils.crypto import get_random_string


def get_code():
    return get_random_string(50)


class Invite(TimeStampedModel):
    id = models.AutoField(primary_key=True)
    code = models.CharField(max_length=50, default=get_code)
    request = models.OneToOneField("Request", on_delete=models.CASCADE)

    def __str__(self):
        return self.code


class Request(TimeStampedModel):
    id = models.AutoField(primary_key=True)
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email

saas_app/blog/models.py
from model_utils.models import TimeStampedModel
from autoslug import AutoSlugField
from slugify import slugify as unicode_slugify
from tinymce.models import HTMLField

from django.db import models
from django.urls import reverse


class Entry(TimeStampedModel):
    id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from="title", slugify=unicode_slugify)
    content = HTMLField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:entry", kwargs={"slug": self.slug})

    class Meta:
        ordering = ("-created",)

saas_app/models/base.py
from django.db import models
from model_utils.models import TimeStampedModel


class BaseModel(TimeStampedModel):
    # If you have additional common fields, define them here

    class Meta:
        abstract = True
        ordering = ["id"]

saas_app/beta/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from saas_app.beta.models import Request


class InviteForm(forms.Form):

    code = forms.CharField(max_length=50, min_length=50)


class RequestForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit("submit", "Submit"))

    class Meta:
        model = Request
        fields = ("email",)

saas_app/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from saas_app.users.models import User


class MyUserCreationForm(UserCreationForm):

    field_order = ["first_name", "email"]

    class Meta(UserCreationForm):
        model = User
        fields = ("first_name", "email")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = user.email  # Use email as username
        if commit:
            user.save()
        return user

saas_app/api/v1/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework import status
from saas_app.api.v1.serializer import (
    UserSerializer,
)  # Adjust the import path as necessary


class CurrentUserView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        serializer = UserSerializer(request.user)
        return Response(serializer.data)

    def put(self, request):
        serializer = UserSerializer(request.user, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

saas_app/app/views.py
from django.views.generic import TemplateView


class DashboardView(TemplateView):

    template_name = "app/dashboard.html"

saas_app/beta/views.py
from allauth.utils import build_absolute_uri

from django.views.generic import CreateView, TemplateView
from django.core.mail import mail_admins
from django.urls import reverse

from saas_app.beta.models import Request
from saas_app.beta.forms import RequestForm


class RequestInviteView(CreateView):
    model = Request
    form_class = RequestForm

    def get_success_url(self):
        return reverse("beta:request-success")

    def form_valid(self, form):
        mail_admins(
            subject="Invite requested",
            message="{email} requested an invite to your beta.\n\n"
            "Manage invites at {admin_url}".format(
                email=form.cleaned_data["email"],
                admin_url=build_absolute_uri(None, "/foo"),
            ),
        )
        return super().form_valid(form)


class RequestInviteSuccess(TemplateView):
    template_name = "beta/request_success.html"

saas_app/blog/views.py
from django.views.generic import ListView, DetailView

from saas_app.blog.models import Entry


class EntryListView(ListView):

    model = Entry
    context_object_name = "entries"
    paginate_by = 5


class EntryView(DetailView):

    model = Entry
    slug_field = "slug"
    slug_url_kwarg = "slug"

saas_app/payments/views.py
import logging
import jwt
from jwt.exceptions import DecodeError
from stripe.error import StripeError, CardError
from stripe import Customer as StripeCustomer

from pinax.stripe.models import Customer
from pinax.stripe.actions.customers import sync_customer
from pinax.stripe.views import (
    PaymentMethodCreateView,
    SubscriptionUpdateView,
    PaymentMethodUpdateView,
)
from pinax.stripe.actions.sources import (
    sync_payment_source_from_stripe_data,
    delete_card,
)
from pinax.stripe.mixins import LoginRequiredMixin

from django import forms
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.utils.encoding import smart_str
from django.conf import settings
from django.views.generic import FormView
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib import messages
from django.http import HttpResponseRedirect

from saas_app.payments.plan import get_plans

logger = logging.getLogger(__name__)


class CustomSubscriptionUpdateView(SubscriptionUpdateView):
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["plans"] = get_plans()
        data["change_button"] = True
        return data

    def update_subscription(self, plan_id):
        super().update_subscription(plan_id)
        # deactivate_exceeding_private_repos.delay(self.request.user.pk)


class CustomPaymentMethodCreateView(PaymentMethodCreateView):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if self.customer is None:
            messages.error(request, "You can't add a card without a subscription")
            return HttpResponseRedirect(reverse("pinax_stripe_subscription_list"))
        return super().dispatch(request, *args, **kwargs)

    def create_card(self, stripe_token):
        for card in self.customer.card_set.all():
            delete_card(self.customer, card.stripe_id)
        source = self.customer.stripe_customer.sources.create(source=stripe_token)
        sync_payment_source_from_stripe_data(self.customer, source)

    def post(self, request, *args, **kwargs):
        try:
            self.create_card(request.POST.get("stripeToken"))
            return redirect("pinax_stripe_subscription_list")
        except CardError as e:
            return self.render_to_response(self.get_context_data(errors=smart_str(e)))


class OctobatForm(forms.Form):

    transactionDetails = forms.CharField()

    def clean_transactionDetails(self):
        details = self.cleaned_data["transactionDetails"]
        try:
            data = jwt.decode(details, settings.OCTOBAT_PRIVATE_KEY)
            customer = data["customer_id"]
            return data
        except DecodeError as e:
            logger.error(
                "Unable to clean transactionDetails for data: {}".format(details),
                exc_info=True,
            )
            raise forms.ValidationError("transaction details could'nt be received")
        except KeyError as e:
            logger.error(
                "Unable to clean transactionDetails for data: {}".format(details),
                exc_info=True,
            )
            raise forms.ValidationError("transaction details could'nt be received")


class CheckoutView(LoginRequiredMixin, FormView):

    form_class = OctobatForm
    template_name = "pinax/stripe/subscription_create.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["plans"] = get_plans()
        data["OCTOBAT_PUBLIC_KEY"] = settings.OCTOBAT_PUBLIC_KEY
        data["OCTOBAT_SUPPLIER_NAME"] = settings.OCTOBAT_SUPPLIER_NAME
        data["OCTOBAT_IMAGE"] = settings.OCTOBAT_IMAGE
        data["octobat_button"] = True
        return data

    def form_valid(self, form):
        trans = form.cleaned_data["transactionDetails"]
        try:
            stripe_customer = StripeCustomer.retrieve(trans["customer_id"])
            cus = Customer.objects.create(
                user=self.request.user, stripe_id=stripe_customer["id"]
            )
            sync_customer(cus, stripe_customer)
            return redirect(reverse("pinax_stripe_subscription_list"))
        except StripeError as e:
            messages.error(
                self.request,
                "Unable to communicate with stripe. Please try again later",
            )
            logger.error(
                "Stripe Error during checkout for customer {}".format(
                    self.request.user
                ),
                exc_info=True,
            )
            return redirect(reverse("pinax_stripe_subscription_list"))

    def form_invalid(self, form):
        messages.error(
            self.request, "Unable to process request. Please contact support."
        )
        return super().form_invalid(form)

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_anonymous():
            if self.request.user.is_customer:
                messages.add_message(
                    request, messages.ERROR, "You already have a subscription"
                )
                return redirect(reverse("pinax_stripe_subscription_list"))
        return super().dispatch(request, *args, **kwargs)

saas_app/users/views.py
from braces.views import LoginRequiredMixin

from django.urls import reverse
from django.views.generic import UpdateView

from .models import User


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = [
        "name",
    ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:update")

    def get_object(self, queryset=None):
        # Only get the User record for the user making the request
        return User.objects.get(pk=self.request.user.pk)

saas_app/views.py
from django.views.generic import TemplateView

from saas_app.payments.plan import get_plans


class PricingView(TemplateView):

    template_name = "pages/pricing.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["plans"] = get_plans(free_plan=True)
        data["col"] = (
            "col-md-{}".format(int(12 / len(data["plans"])))
            if len(data["plans"])
            else "col-md-4"
        )
        return data

saas_app/templates/app/base.html
{% load static compress %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <meta name="robots" content="{% block robots %}noindex,follow{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    {% compress css %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/LineIcons.css' %}">
    <link rel="stylesheet" href="{% static 'css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fullcalendar.css' %}">
    <link rel="stylesheet" href="{% static 'css/fullcalendar.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% endcompress %}
    {% compress css %}
    <link href="{% static 'css/app.css' %}" rel="stylesheet">
    {% endcompress %}
    {% endblock %}
    {% block css_extra %}
    {% endblock %}
  </head>

  <body>

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url "app:dashboard" %}">
            <img src="{% static "images/logo.png" %}"/>
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li>
              {% comment %} <a href="{% url "pinax_stripe_subscription_list" %}"> {% endcomment %}
                Subscription
              </a>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url "users:update" %}">Profile</a></li>
                  <li><a href="{% url "account_set_password" %}">Password</a></li>
                  <li><a href="{% url "account_email" %}">Email</a></li>
                </ul>
              </li>
            <li><a href="{% url "account_logout" %}"><i class="fa fa-sign-out"></i> </a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid" id="app">
      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}
      <div class="row">
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          {% block content %}

          {% endblock %}
        </div>
      </div>
    </div>

    {% block javascript %}
      <!-- Latest JQuery -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/bootstrap.js' %}"></script>
      <script src="{% static 'js/project.js' %}"></script>
      <script src="{% static 'js/Chart.min.js' %}"></script>
      <script src="{% static 'js/dynamic-pie-chart.js' %}"></script>
      <script src="{% static 'js/moment.min.js' %}"></script>
      <script src="{% static 'js/fullcalendar.js' %}"></script>
      <script src="{% static 'js/jvectormap.min.js' %}"></script>
      <script src="{% static 'js/world-merc.js' %}"></script>
      <script src="{% static 'js/polyfill.js' %}"></script>

      {% endcompress %}
    {% endblock javascript %}
    {% block javascript_extra %}
    {% endblock %}
  </body>
</html>

saas_app/templates/app/dashboard.html
{% extends "app/base.html" %}
{% load render_bundle from webpack_loader %}

{% block title %}Dashboard{% endblock %}

{% block content %}
  This is where your app kicks in.
{% endblock %}


{% block javascript_extra %}
  {% render_bundle 'vendor' %}
  {% render_bundle 'main' %}
{% endblock %}